version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: updoc
      POSTGRES_PASSWORD: updoc
      POSTGRES_DB: updoc
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
